package:
  name: apko
  version: 0.17.0
  epoch: 2
  description: should have bumped the epoch
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/chainguard-dev/apko
      tag: v${{package.version}}
      expected-commit: 636d87f1c66181d4f1ff146595ddc157a033f723
